### ISSUE TITLE
Update stable version in repo from 0.6.3 to 0.6.7

### ISSUE THREAD

**Issue by GermanBluefox** [DrozmotiX/ioBroker.coronavirus-statistics#162]
# Think about update stable version to 0.6.7
**Version**: stable=**0.6.3** (76 days old) => latest=**0.6.7** (15 days old)
**Installs**: stable=**2108** (60.91%), latest=**701** (20.25%), total=**3461**
Click to [edit](https://github.com/ioBroker/ioBroker.repositories/edit/master/sources-dist-stable.json#L152)

**Comment by DutchmanNL** [comment]
will wait for testing results of https://github.com/DrozmotiX/ioBroker.coronavirus-statistics/releases/tag/v0.6.9 for 1 week

**Comment by DutchmanNL** [comment]
found an additional issue for Germany vaccination and fixed, let wait for sentry reporting

**Comment by RkcCorian** [comment]
First of all many thanks for the adapter and your work!!
Officially in ioBroker I still see "only" the version 0.6.3 but I'm very interested in the vaccination rate. It would be very very nice to get this as stable version via the "official" installation way. Can we expect this within the next days?

**Comment by DutchmanNL** [comment]
> First of all many thanks for the adapter and your work!!
> Officially in ioBroker I still see "only" the version 0.6.3 but I'm very interested in the vaccination rate. It would be very very nice to get this as stable version via the "official" installation way. Can we expect this within the next days?

end of this week, thew was a lot of error with RKI data we needed to manage

**Comment by DutchmanNL** [comment]
https://github.com/ioBroker/ioBroker.repositories/pull/1396
