### ISSUE TITLE
No update every 15 minutes ?

### ISSUE THREAD

**Issue by radebold** [DrozmotiX/ioBroker.coronavirus-statistics#173]
Hi team,

i run the version 0.6.8

My feeling is the it will not refresh in this intervalls.
If I look directly into https://services7.arcgis.com..... it is not actually

I setup a refresh intervall of every hour, but the change is come on diff times.
What is wrong?

e.g. (cases7_per_100k_txt)
Adapter shows: 46,5 (last update 04.02.2020 - 14:21 [looks like my last reboot])
portal: 47,6 (last update 05.02.2020 - 00:00)
https://services7.arcgis.com/mOBPykOjAyBO2ZKk/arcgis/rest/services/RKI_Landkreisdaten/FeatureServer/0/query?where=county%20%3D%20%27LK%20G%C3%96PPINGEN%27&outFields=last_update,cases7_per_100k,cases7_per_100k_txt&outSR=4326&f=json

thx for the adapter and support

**Comment by DutchmanNL** [comment]
data only refresh if the API is available and provides new values, no new values = data stays the same
