### ISSUE TITLE
adapter shows no status

### ISSUE THREAD

**Issue by radebold** [DrozmotiX/ioBroker.coronavirus-statistics#174]
![image](https://user-images.githubusercontent.com/25064101/107004200-3ceb4280-678e-11eb-95de-0fcf4fd25da8.png)

Why the adapter not show the green, red, yellow or gray flag ?

**Comment by DutchmanNL** [comment]
> ![image](https://user-images.githubusercontent.com/25064101/107004200-3ceb4280-678e-11eb-95de-0fcf4fd25da8.png)
> 
> Why the adapter not show the green, red, yellow or gray flag ?

its an scheduled adapter, so only runs for a few minutes that will wait until the next run.
This kind of scheduled adapter do not have a status connected etc :)
