### ISSUE TITLE
Cannot get Vaccination data for germany Error: Corrupted zip : can't find end of central directory

### ISSUE THREAD

**Issue by vaaarg** [DrozmotiX/ioBroker.coronavirus-statistics#175]
adapter v0.6.8
pi4
Node.js v12.20.1
NPM 6.14.10

`coronavirus-statistics.0	2021-02-07 11:19:19.020	info	(29795) Terminated (ADAPTER_REQUESTED_TERMINATION): All data handled, adapter stopped until next scheduled moment
coronavirus-statistics.0	2021-02-07 11:19:18.793	error	(29795) Cannot get Vaccination data for germany Error: Corrupted zip : can't find end of central directory
coronavirus-statistics.0	2021-02-07 11:15:02.414	info	(29795) starting. Version 0.6.8 in /opt/iobroker/node_modules/iobroker.coronavirus-statistics, node: v12.20.1, js-controller: 3.2.13
host.raspberrypi	2021-02-07 11:15:00.072	info	instance system.adapter.coronavirus-statistics.0 started with pid 29795
host.raspberrypi	2021-02-07 11:03:57.370	info	instance system.adapter.coronavirus-statistics.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
coronavirus-statistics.0	2021-02-07 11:03:56.843	info	(29678) Terminated (ADAPTER_REQUESTED_TERMINATION): All data handled, adapter stopped until next scheduled moment
coronavirus-statistics.0	2021-02-07 11:03:56.688	error	(29678) Cannot get Vaccination data for germany Error: Corrupted zip : can't find end of central directory`

getting these errors. uninstall reinstall nothing helped.

**Comment by DutchmanNL** [comment]
solved in latest
