### ISSUE TITLE
Germany / RKI changed spreadsheet for vaccination

### ISSUE THREAD

**Issue by Supermicha81** [DrozmotiX/ioBroker.coronavirus-statistics#176]
since tody, AstraZeneca is listet, so other values changed their position in the table.

e.g. rkiImpfQuote shows values from DifferenzVortag

**Comment by lembnau** [comment]
I have made a change to the adapter that it works again now. I only do not know, what to do to make that public :-)

**Comment by lembnau** [comment]
> since tody, AstraZeneca is listet, so other values changed their position in the table.
> 
> e.g. rkiImpfQuote shows values from DifferenzVortag

I have changed / corrected the script. Not sure, what to do with it now..

**Comment by Schiri** [comment]
@lembnau I think u just need to create a pull request with your changes from your fork into this repo

**Comment by DutchmanNL** [comment]
> I have changed / corrected the script. Not sure, what to do with it now..

i was just rewriting the code, can you share your part ?
I will include the generic API, for Germany its always changing but happy to keep it in

**Comment by DutchmanNL** [comment]
@lembnau I created a new Branch and picked your commits, hope that's ok for you ?
Will test this setup and if all works I will release it as a new version :)

https://github.com/DrozmotiX/ioBroker.coronavirus-statistics/tree/mergeChangesLembnau

**Comment by DutchmanNL** [comment]
@lembnau ich bedankt mich herzlich ! Habe deinen branch gemerged damit hast du dir ewigen room auf den commits und der readme dieses adapter gesichert :)

https://github.com/DrozmotiX/ioBroker.coronavirus-statistics/releases/tag/v0.6.9

Ab morgen im admin installierbar, ich warte eine Woche bis ich die version nach stable bringe
