### ISSUE TITLE
Plain text file (csv) source for german vaccination data instead of excel spreadsheet

### ISSUE THREAD

**Issue by xdaamg** [DrozmotiX/ioBroker.coronavirus-statistics#177]
RKI links to www.impfdashboard.de to present vaccination data for germany.

Under https://impfdashboard.de/daten you find two csv-files (plain text) with daily vaccination data, for example https://impfdashboard.de/static/data/germany_vaccinations_timeseries_v2.tsv. It should be more easy to handle those data than excel spreadsheet used now. I think there is also more information provided in these files.

![grafik](https://user-images.githubusercontent.com/13882366/107504437-92af5880-6b9b-11eb-9445-1ae684b91302.png)

![grafik](https://user-images.githubusercontent.com/13882366/107504374-77444d80-6b9b-11eb-989a-8699bd6a6ae7.png)

**Comment by jhg28** [comment]
Any update to this issue?
The data are still missing and in the meanwhile also the other data are not updated since 1 week.

**Comment by DutchmanNL** [comment]
solved in https://github.com/DrozmotiX/ioBroker.coronavirus-statistics/releases/tag/v0.6.9
