### ISSUE TITLE
7 day incidence for germany

### ISSUE THREAD

**Issue by ghostrider95** [DrozmotiX/ioBroker.coronavirus-statistics#188]
it would be nice if the 7 day incidence of whole germany could be added.

i also wanted to calculate the 7 day incidence of whole germany via all federal states of germany but there is no value of "cases in last 7 days" at the federal states.. only "cases7_100k" and "cases_100k". so i can not calculate the 7 day incidence of whole germany in iobroker

**Comment by tecfreakz** [comment]
It's possible to calculate an average in a simple blocky. Rounding on 2 digits after comma by using all incidences of "Bundesländer".

![image](https://user-images.githubusercontent.com/12476459/111613127-7b890980-87de-11eb-985d-f1f8abee1942.png)

**Comment by DutchmanNL** [comment]
sorry but the API does not provide a 7-day status for Germany so I am not able to implement that.

<img width="360" alt="Schermafbeelding 2021-03-22 om 16 29 17" src="https://user-images.githubusercontent.com/7318445/112015055-c16e0680-8b2b-11eb-9db6-d5d932b30e6d.png">


> "cases in last 7 days" at the federal states.. only "cases7_100k" and "cases_100k". so i can not calculate the 7 day incidence of whole germany in iobroker

same issue here, if the data is not providing I cannot include it :)

**Comment by DutchmanNL** [comment]
> It's possible to calculate an average in a simple blocky. Rounding on 2 digits after comma by using all incidences of "Bundesländer".
> 
> ![image](https://user-images.githubusercontent.com/12476459/111613127-7b890980-87de-11eb-985d-f1f8abee1942.png)

if it adds value, I am happy to include this script into the adapter logic as a generic value ?

**Comment by lembnau** [comment]
We could read that with the API from [https://rki.marlon-lueckert.de/api/general](url)
But that giveas back some Objects, i don't know how to handle until now

**Comment by DutchmanNL** [comment]
> We could read that with the API from [https://rki.marlon-lueckert.de/api/general](url)
> But that giveas back some Objects, i don't know how to handle until now

if you are willing to work in it I am happy to help you out with the objects, myself I just can't find time currently to do it :/

**Comment by DutchmanNL** [comment]
as we have no progress here or solution I am closing it for now. If the request iss still valid please feel free to reopen or provide an update comment
