### ISSUE TITLE
State attribute definition missing for + countryInfo

### ISSUE THREAD

**Issue by s0n1c** [DrozmotiX/ioBroker.coronavirus-statistics#19]
Aktuell kommt es zum folgenden Fehler...

coronavirus-statistics.0 | 2020-03-24 10:30:36.909 | warn | (18092) State attribute definition missing for + countryInfo
-- | -- | -- | --
coronavirus-statistics.0 | 2020-03-24 10:30:36.777 | warn | (18092) State attribute definition missing for + countryInfo
coronavirus-statistics.0 | 2020-03-24 10:30:36.657 | warn | (18092) State attribute definition missing for + countryInfo
coronavirus-statistics.0 | 2020-03-24 10:30:36.536 | warn | (18092) State attribute definition missing for + countryInfo
coronavirus-statistics.0 | 2020-03-24 10:30:36.367 | warn | (18092) State attribute definition missing for + countryInfo
coronavirus-statistics.0 | 2020-03-24 10:30:36.248 | warn | (18092) State attribute definition missing for + countryInfo
coronavirus-statistics.0 | 2020-03-24 10:30:36.075 | warn | (18092) State attribute definition missing for + countryInfo
coronavirus-statistics.0 | 2020-03-24 10:30:35.890 | warn | (18092) State attribute definition missing for + countryInfo
coronavirus-statistics.0 | 2020-03-24 10:30:35.883 | warn | (18092) Turks_and_Caicos not found in lib! Must be added to the country name translator.
coronavirus-statistics.0 | 2020-03-24 10:30:34.089 | warn | (18092) State attribute definition missing for + countryInfo
coronavirus-statistics.0 | 2020-03-24 10:30:33.930 | warn | (18092) State attribute definition missing for + countryInfo
coronavirus-statistics.0 | 2020-03-24 10:30:28.217 | warn | (18092) Error getting API response, will retry at next shedule

**Comment by s0n1c** [comment]
Und vielen Dank für den Adapter! Ich habe somit eine automatische Berechnung für die Auslastung der Beatmungsplätze in Deutschland herstellen können.

**Comment by DutchmanNL** [comment]
interessant, das mit dem attribute ist übrigens mit der version 0.4.0 gefixt die heute in default kommt

Als beta test stehen die bunddeslaender jetzt bereit

**Comment by viab23** [comment]
Ich bekomme unter 0.6.3 plötzlich wieder die Meldung "State attribute definition missing for + undefined", woher kommt das?

**Comment by DutchmanNL** [comment]
> Ich bekomme unter 0.6.3 plötzlich wieder die Meldung "State attribute definition missing for + undefined", woher kommt das?

muss ich mir anschauen wahrscheinlich ne API aenderung :/

**Comment by DutchmanNL** [comment]
fixed
