### ISSUE TITLE
No update since 2 days

### ISSUE THREAD

**Issue by chrkraus** [DrozmotiX/ioBroker.coronavirus-statistics#195]
Hello everyone, 
I did not get any updates since two days. The RKI is updated.

For example:
Germany --> Bundesland: Bayern --> Kreis "Neustadt_ad_Waldnaab

Many thanks

**Comment by xdaamg** [comment]
coronavirus-statistics.0 | 2021-03-18 10:00:25.754 | error | at Covid19.onReady (/opt/iobroker/node_modules/iobroker.coronavirus-statistics/main.js:635:5)
-- | -- | -- | --
coronavirus-statistics.0 | 2021-03-18 10:00:25.754 | error | at processTicksAndRejections (internal/process/task_queues.js:97:5)
coronavirus-statistics.0 | 2021-03-18 10:00:25.754 | error | at runMicrotasks (<anonymous>)
coronavirus-statistics.0 | 2021-03-18 10:00:25.754 | error | at germanyCounties (/opt/iobroker/node_modules/iobroker.coronavirus-statistics/main.js:512:35)
coronavirus-statistics.0 | 2021-03-18 10:00:25.754 | error | (3853) [germanyCounties] error: values.features is not iterable, stack: TypeError: values.features is not iterable

**Comment by DutchmanNL** [comment]
should be solved by 0.6.9

https://github.com/DrozmotiX/ioBroker.coronavirus-statistics/releases/tag/v0.6.9
