### ISSUE TITLE
Sorry, Adapter stop working 

### ISSUE THREAD

**Issue by buehlisiobroker** [DrozmotiX/ioBroker.coronavirus-statistics#225]
Der Adapter holt sich leider keine Daten mehr, es wird immer an der gleiche Stelle abgebrochen.
Ich habe auch bereits verschiedene Versionen getestet, nur ohne Erfolg.
![image](https://user-images.githubusercontent.com/79419654/112888006-1da8cb80-90d4-11eb-80b6-1d7695a209a2.png)
Wäre super, wenn sich da einer mal anschauen könnte.
Danke!
 
 - Adapter version: 0.6.9
 - JS-Controller version: 3.2.16
 - Node version: 12.21.0
 - Operating system: Linux

**Comment by DutchmanNL** [comment]
was geht nicht ? Adapter laueft laut deinem log,  er stop nach jedem Intervall das is normal.
PS: letztere Version auch fuer Impfungen ist die 0.7 wird ende Woche nach stable gehen
