### ISSUE TITLE
"Impfungen" objects filled with wrong values

### ISSUE THREAD

**Issue by xdaamg** [DrozmotiX/ioBroker.coronavirus-statistics#228]
I noticed, objects under "_Impfungen" are not filled with valid data today.

For example these objects are not filled or contain wrong data:

coronavirus-statistics.0.Germany._Impfungen.rkiErstimpfungenAstraZeneca
coronavirus-statistics.0.Germany._Impfungen.rkiErstimpfungenBioNTech
coronavirus-statistics.0.Germany._Impfungen.rkiErstimpfungenDifferenzVortag
coronavirus-statistics.0.Germany._Impfungen.rkiErstimpfungenImpfquote
coronavirus-statistics.0.Germany._Impfungen.rkiErstimpfungenModerna
coronavirus-statistics.0.Germany._Impfungen.rkiZweitimpfungenAstraZeneca
coronavirus-statistics.0.Germany._Impfungen.rkiZweitimpfungenBioNTech
coronavirus-statistics.0.Germany._Impfungen.rkiZweitimpfungenDifferenzVortag
coronavirus-statistics.0.Germany._Impfungen.rkiZweitimpfungenImpfquote
coronavirus-statistics.0.Germany._Impfungen.rkiZweitimpfungenModerna

**Comment by Elvissimo** [comment]
also fields for vaccination doses in total contain old values from 2-3 days ago

**Comment by jhg28** [comment]
Still the same issue.
Any update?

**Comment by saint-hh** [comment]
11 days and counting. Would be nice if we get to know if it will be fixed or we should seek for a workaround ourselves. 
Thank you!

**Comment by tmycgn** [comment]
A workaround might be to use the following new source: https://corona-open-data.ckan.de/

For Germany, the following sources seem official and up-to-date:

https://impfdashboard.de/static/data/germany_vaccinations_timeseries_v2.tsv
https://impfdashboard.de/static/data/germany_vaccinations_by_state.tsv

**Comment by Apollon77** [comment]
> 11 days and counting

Where is your PR to fix it? Else you need to wait until the developer finds time to check and fix this issue

**Comment by xdaamg** [comment]
I solved this issue for now by using 'parser-adapter'. Source is rki website 'impfdashboard.de'. Objects:

<img width="1304" alt="Screenshot_parser_rkidashboard_result" src="https://user-images.githubusercontent.com/13882366/119152935-0db4c480-ba51-11eb-9159-d2b0d792a49d.png">

Parser-Adapter settings:
[iobroker_parser_rkidashboard.txt](https://github.com/DrozmotiX/ioBroker.coronavirus-statistics/files/6523159/iobroker_parser_rkidashboard.txt)

**Comment by DutchmanNL** [comment]
> > 11 days and counting
> 
> Where is your PR to fix it? Else you need to wait until the developer finds time to check and fix this issue

that would indeed help a lot I currently just have no time to do it for now, the code is pretty simple only these lines here : 

https://github.com/DrozmotiX/ioBroker.coronavirus-statistics/blob/main/main.js#L352-L380

**Comment by DutchmanNL** [comment]
solved release v0.7.0-5
