### ISSUE TITLE
Werte vom Vortag speichern

### ISSUE THREAD

**Issue by Fritzelspitze** [DrozmotiX/ioBroker.coronavirus-statistics#231]
Um die Differenz zum Vortag zu haben würde ich mir wünschen, dass die Werte vom Vortag von dem Adapter selbst gespeichert werden damit man die Differenz der Inzidenz auf Städteeben anzeigen kann.

**Comment by Elvissimo** [comment]
dafür brauchst Du eigentlich keine Änderung im Adapter, Du kannst Dir doch einfach einen Wert per Script in einen individuell angelegten Wert schreiben und diesen täglich verschieben. Ich mache das für 20 Werte der 7-Tage-Inzidenz unseres Landkreises und bekomme so einen guten Überblick der letzten Wochen als Balkendiagramm in VIS dargestellt. Nur so als Idee.

**Comment by DutchmanNL** [comment]
der adapter ist dafuer concipiert die API-daten ab zu fragen, eventuelles logging ist per Stript oder SQL/Influx moeglich wir probieren die Komplexität in adapteert Strukturen fuer die maintainability so klein wie moeglich zu halten :)
