### ISSUE TITLE
Definition missing for + undefined

### ISSUE THREAD

**Issue by testit2020** [DrozmotiX/ioBroker.coronavirus-statistics#234]
coronavirus-statistics.0 | 2021-04-23 17:45:13.567 | warn | (32730) State attribute definition missing for + undefined

**Versions:**  
 - Adapter version: 0.7.0-4
 - JS-Controller version:  3.2.16
 - Node version: v12.22.1
 - Operating system: linux

**Comment by vaaarg** [comment]
me2

**Comment by sigi2345** [comment]
Dito
Adapter Version: 0.7.0-4

Plattform: Windows
RAM: 16 GB 
Node.js: 12.21.0
NPM: 6.14.11
JS Controller: 3.2.16
Admin: 5.0.8
Web: 3.4.0
Socket.io: 3.1.4
Script Engine: 5.1.3

**Comment by Landmilch71** [comment]
Same here:
Adapter 0.7.0-4

Platform  linux
Betriebssystem  linux
Architektur  arm
CPUs  4
Geschwindigkeit  800 MHz
Modell  ARMv7 Processor rev 3 (v7l)
RAM  3.74 GB
Node.js  v12.22.1
NPM  6.14.12
JS Controller: 3.2.16
Festplatte Größe  109.78 GB
Festplatte frei  103.16 GB
Anzahl der Adapter  411
Aktive Instanzen  24

**Comment by Lashandan** [comment]
Same here:
Adapter 0.7.0-4

Platform
linux
Betriebssystem
linux
Architektur
arm
CPUs
4
Geschwindigkeit
700 MHz
Modell
ARMv7 Processor rev 3 (v7l)
RAM
7.69 GB
Node.js
v12.22.1
NPM
6.14.12
Anzahl der Adapter
340
Aktive Instanzen
20

**Comment by sbormann** [comment]
Problem still exists:
![image](https://user-images.githubusercontent.com/49171332/120063954-2123e900-c06a-11eb-8d44-ae879124a36b.png)

**Comment by DutchmanNL** [comment]
solved release v0.7.0-5
