### ISSUE TITLE
"Impfquote" values are 'null %'

### ISSUE THREAD

**Issue by bfelizardo** [DrozmotiX/ioBroker.coronavirus-statistics#238]
**Describe the bug**  
Entities: 'rkiErstimpfungenImpfquote' and 'rkiZweitimpfungenImpfquote' get value 'null %'. Since few week I do not get any valid value anymore.

**To Reproduce**  
1. Go to 'objects'
2. Click on 'coronavirus-statistics.0.Germany._Impfungen'
3. Scroll down to 'rkiErstimpfungenImpfquote' and 'rkiZweitimpfungenImpfquote' 
4. See error 'null %'

**Expected behavior**  
There should be a valid value like '25.72 %' or similar.

**Screenshots & Logfiles**  
<img width="1521" alt="Screenshot 2021-04-30 at 16 06 39" src="https://user-images.githubusercontent.com/28575392/116706926-0c4e2a00-a9c6-11eb-9586-5ead662df1fd.png">

**Versions:**  
 - Adapter version: <0.7.0-4>
 - JS-Controller version: <3.2.16>
 - Node version: <12.22.1>
 - Operating system: <linux>

**Comment by luebke01** [comment]
Die Werte sind einfach durcheinander.
Aktuell ist es der Wert für die Erstimpfquote:
coronavirus-statistics.0.Germany._Impfungen.rkiErstimpfungenAstraZeneca
für komplett Geimpfte:
coronavirus-statistics.0.Germany._Impfungen.rkiZweitimpfungenBioNTech

**Comment by bfelizardo** [comment]
@luebke01 ahh danke für den Hinweis. Trotzdem ein Bug oder? @DutchmanNL

**Comment by DutchmanNL** [comment]
> @luebke01 ahh danke für den Hinweis. Trotzdem ein Bug oder? @DutchmanNL

ja bug, ich warte immernoch auf eine vernünftige API source fuer die Impfungen :.

**Comment by jlssmt** [comment]
@DutchmanNL 
> ja bug, ich warte immernoch auf eine vernünftige API source fuer die Impfungen :.

Hier gibts alle Corona Daten inkl. Impfungen per csv (~25MB):
`https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/owid-covid-data.csv
`oder per json:
`https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/owid-covid-data.json
`
Und hier nur die Impfungen per csv (~2MB):
`https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/vaccinations/vaccinations.csv
`Oder per json:
`https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/vaccinations/vaccinations.json
`
Das ist auch die Quelle die Google verwendet.

**Comment by DutchmanNL** [comment]
solved release v0.7.0-5
