### ISSUE TITLE
rkiErstimpfungen falsche Werte

### ISSUE THREAD

**Issue by amg666** [DrozmotiX/ioBroker.coronavirus-statistics#253]
Die Datenpunkte rkiErstimpfungenAstraZeneca, ...BioNTech und ...Moderna stimmen nicht.

Datenpunkt im ioBroker:
AstraZeneca: 37.38825742 (3,7 Milliarden ???)
BioNTech: 31094584
Moderna: 9548021

Laut RKI sind die Werte aber
AstrZeneca: 9,5 Mio
BioNTech: 32 Mio
Moderna: 4,2 Mio

Sieht nach einem Fehler im Parser aus, hat rki da die Seitenstruktur geändert (?)

Adapterversion 0.7.0-4

**Comment by DutchmanNL** [comment]
#238
