### ISSUE TITLE
no data update today

### ISSUE THREAD

**Issue by MrRaspberry** [DrozmotiX/ioBroker.coronavirus-statistics#264]
EDIT: Fixed after updating Adapter from 0.6.93 to 0.7.0-4 ;-)

ioBroker-Log showing this errormessage:

coronavirus-statistics.0 | 2021-06-08 14:24:47.755 | warn | (11361) Terminated (UNCAUGHT_EXCEPTION): Without reason
-- | -- | -- | --
coronavirus-statistics.0 | 2021-06-08 14:24:47.754 | info | (11361) terminating
coronavirus-statistics.0 | 2021-06-08 14:24:47.238 | error | (11361) Cannot read property 'captureException' of undefined
coronavirus-statistics.0 | 2021-06-08 14:24:47.238 | error | at Covid19.onReady (/opt/iobroker/node_modules/iobroker.coronavirus-statistics/main.js:665:9)
coronavirus-statistics.0 | 2021-06-08 14:24:47.238 | error | at Covid19.errorHandling (/opt/iobroker/node_modules/iobroker.coronavirus-statistics/main.js:859:37)
coronavirus-statistics.0 | 2021-06-08 14:24:47.238 | error | (11361) TypeError: Cannot read property 'captureException' of undefined
coronavirus-statistics.0 | 2021-06-08 14:24:47.238 | error | (11361) unhandled promise rejection: Cannot read property 'captureException' of undefined
coronavirus-statistics.0 | 2021-06-08 14:24:47.237 | error | (11361) Unhandled promise rejection. This error originated either by  throwing inside of an async function without a catch block, or by  rejecting a promise which was not handled with .catch().
coronavirus-statistics.0 | 2021-06-08 14:24:47.237 | error | at async Covid19.onReady (/opt/iobroker/node_modules/iobroker.coronavirus-statistics/main.js:653:5)
coronavirus-statistics.0 | 2021-06-08 14:24:47.237 | error | at germanyBundersland (/opt/iobroker/node_modules/iobroker.coronavirus-statistics/main.js:508:11)
coronavirus-statistics.0 | 2021-06-08 14:24:47.237 | error | at Covid19.errorHandling (/opt/iobroker/node_modules/iobroker.coronavirus-statistics/main.js:859:37)
coronavirus-statistics.0 | 2021-06-08 14:24:47.237 | error | (11361) [onReady] error: Cannot read property 'captureException' of  undefined, stack: TypeError: Cannot read property 'captureException' of  undefined
coronavirus-statistics.0 | 2021-06-08 14:24:47.236 | error | at async Covid19.onReady (/opt/iobroker/node_modules/iobroker.coronavirus-statistics/main.js:653:5)
coronavirus-statistics.0 | 2021-06-08 14:24:47.236 | error | at germanyBundersland (/opt/iobroker/node_modules/iobroker.coronavirus-statistics/main.js:474:142)
coronavirus-statistics.0 | 2021-06-08 14:24:47.236 | error | (11361) [germanyFederalStates] error: Cannot read property  'Erstimpfung' of undefined, stack: TypeError: Cannot read property  'Erstimpfung' of undefined

**Comment by DutchmanNL** [comment]
solved release v0.7.0-5
