### ISSUE TITLE
Vaccination Data still incorrect

### ISSUE THREAD

**Issue by jhg28** [DrozmotiX/ioBroker.coronavirus-statistics#277]
Also with the Version 0.7.0 issues with the vaccination data.

RKI Erstimpfung is as before not updated.
Last update was from 25th May.
And the percentages from 1st and 2nd vaccination is also not updated.

And there is a new error Message:
Cannot handle vaccination data for Germany fromm RKI, if this erros continues please report a bug to the developen!

**Comment by vaaarg** [comment]
`
<html>
<body>


coronavirus-statistics.0 | 2021-06-29 08:00:15.766 | warn | (2071) Cannot handle vaccination data for Germany fromm RKI, if this erros continues please report a bug to the developen!
-- | -- | -- | --
coronavirus-statistics.0 | 2021-06-29 08:00:15.706 | warn | (2071) Cannot handle vaccination data for Germany fromm RKI, if this erros continues please report a bug to the developen!
coronavirus-statistics.0 | 2021-06-29 08:00:15.630 | warn | (2071) Cannot handle vaccination data for Germany fromm RKI, if this erros continues please report a bug to the developen!


</body>
</html>`

**Comment by jhg28** [comment]
<img width="1725" alt="Bildschirmfoto 2021-06-29 um 21 03 25" src="https://user-images.githubusercontent.com/16444163/123853252-88f57a00-d91d-11eb-95b9-45fa26dba790.png">

Der Fehler tritt bei den bundesweiten Daten der Impfung auf.

**Comment by DutchmanNL** [comment]
Habe seit 18.45 auch Fehler im log, schaue morgen

**Comment by DutchmanNL** [comment]
solved in [0.7.1](https://github.com/DrozmotiX/ioBroker.coronavirus-statistics/commit/935f54c13407b993469e399cf575adfeb6e63cd9)
