### ISSUE TITLE
Cannot handle vaccination data for Germany fromm RKI

### ISSUE THREAD

**Issue by Supermicha81** [DrozmotiX/ioBroker.coronavirus-statistics#278]
I don't know if it is the same problem like #277

I've updated to 0.7.0 an now my log says:
`warn: coronavirus-statistics.0 (16965) Cannot handle vaccination data for Germany fromm RKI, if this erros continues please report a bug to the developen!`

This entry appears 17 time if the adapter is started.

the recieved data for the bundesländer seems to be correct. the data for whole germany is just NULL.

**Comment by DutchmanNL** [comment]
duplicate #277
