### ISSUE TITLE
Warning in log: "Cannot handle vaccination data of Germany for ..."

### ISSUE THREAD

**Issue by TbsBrggng** [DrozmotiX/ioBroker.coronavirus-statistics#298]
**Describe the bug**  

got several warnings in the logs, e.g.:

1)
Cannot handle vaccination data of Germany for Totals from RKI, if this error continues please report a bug to the developer! Totals: {"":0,"_1":"Gesamt","Gesamtzahl bisher verabreichter Impfungen":89387257,"Gesamtzahl mindestens einmal geimpft* ":50643772,"Gesamtzahl vollständig geimpft*":41073682,"Impfquote mindestens einmal geimpft ":60.9,"_2":18.4,"_3":61,"_4":84.8,"Impfquote vollständig geimpft ":49.4,"_5":7.8,"_6":48.8,"_7":77.5,"__EMPTY":0,"__EMPTY_1":0,"__EMPTY_2":0,"__EMPTY_3":0}

2) 
Cannot handle vaccination data of Germany for Thüringen from RKI, if this errors continues please report a bug to the developed! Bundesland : {"":16,"_1":"Thüringen","Gesamtzahl bisher verabreichter Impfungen":2163728,"Gesamtzahl mindestens einmal geimpft* ":1174064,"Gesamtzahl vollständig geimpft*":1034982,"Impfquote mindestens einmal geimpft ":55,"_2":14.8,"_3":51.1,"_4":78.5,"Impfquote vollständig geimpft ":48.5,"_5":10.9,"_6":45.3,"_7":73.2,"__EMPTY":0,"__EMPTY_1":0,"__EMPTY_2":0,"__EMPTY_3":0}

3)
Cannot handle vaccination data of Germany for Nordrhein-Westfalen from RKI, if this errors continues please report a bug to the developed! Bundesland : {"":"05","_1":"Nordrhein-Westfalen","Gesamtzahl bisher verabreichter Impfungen":20198566,"Gesamtzahl mindestens einmal geimpft* ":11522493,"Gesamtzahl vollständig geimpft*":9249100,"Impfquote mindestens einmal geimpft ":64.2,"_2":19.7,"_3":64.7,"_4":88.5,"Impfquote vollständig geimpft ":51.5,"_5":7.7,"_6":51.6,"_7":80.8,"__EMPTY":0,"__EMPTY_1":0,"__EMPTY_2":0,"__EMPTY_3":0}

**To Reproduce**  
adapter is just running and refreshing data from source.

**Expected behavior**  

**Screenshots & Logfiles**  

**Versions:**  
 - Adapter version: v 0.7.1
 - JS-Controller version: 3.3.14
 - Node version: 12.22.2
 - Operating system: x86_64 GNU/Linux

**Additional context**

**Comment by vaaarg** [comment]
`
<html>
<body>


coronavirus-statistics.0 | 2021-07-27 08:00:10.672 | warn | (21030) Cannot handle vaccination data of Germany for Totals from RKI, if this error continues please report a bug to the developer! Totals: {"":0,"_1":"Gesamt","Gesamtzahl bisher verabreichter Impfu
-- | -- | -- | --
coronavirus-statistics.0 | 2021-07-27 08:00:10.616 | warn | (21030) Cannot handle vaccination data of Germany for Thüringen from RKI, if this errors continues please report a bug to the developed! Bundesland : {"":16,"_1":"Thüringen","Gesamtzahl bisher verabr
coronavirus-statistics.0 | 2021-07-27 08:00:10.544 | warn | (21030) Cannot handle vaccination data of Germany for Baden-Württemberg from RKI, if this errors continues please report a bug to the developed! Bundesland : {"":"08","_1":"Baden-Württemberg","Gesamt


</body>
</html>`

**Comment by Maj0rT** [comment]
Can you please fix this?

warn | Cannot handle vaccination data of Germany for Totals from RKI, if this error continues please report a bug to the developer! Totals: {"":0,"_1":"Gesamt","Gesamtzahl bisher verabreichter Impfungen":92700668,"Gesamtzahl mindestens einmal geimpft* ":51423707,"Gesamtzahl vollständig geimpft*":43708441,"Impfquote mindestens einmal geimpft ":61.8,"_2":20.7,"_3":62.2,"_4":85.2,"Impfquote vollständig geimpft ":52.6,"_5":10.1,"_6":53.2,"_7":79.8,"__EMPTY":0,"__EMPTY_1":0,"__EMPTY_2":0,"__EMPTY_3":0}
-- | --

Thanks in advance,
Torsten

**Comment by TbsBrggng** [comment]
Hey @DutchmanNL,
any ideas? 
regards,
Tobias

**Comment by DutchmanNL** [comment]
> Hey @DutchmanNL,
> any ideas?
> regards,
> Tobias

please test 0.8.0-1 :)

**Comment by DutchmanNL** [comment]
> Hi DutchmanNL,
> gerade ausprobiert. Die 0.8.0-1 holt die aktuelle Impfdaten (Debug Log Zeile 5784-5796 für BW und 5941-5950 für BRD) aber er schreibt Sie nur im Bundesland (bei mir BW) in die ObjektID rein, nicht aber für Deutschland. Die Daten sind noch vom 23.07.21
> [iobroker.2021-08-11_corona.log](https://github.com/DrozmotiX/ioBroker.coronavirus-statistics/files/6967784/iobroker.2021-08-11_corona.log)
> ![2021-08-11 12_47_41-objects - raspi-iob](https://user-images.githubusercontent.com/80831456/129016879-c046d700-0bb3-4424-a118-40bfb0836d78.png)
> 
> Danke für Deine Bemühungen.

Die gesamt Daten fuer DE werden aus einer anderen API gezogen und befinden sich unter Vaccination.
Nur die bundeslaender kommen direkt vom RKI Datensatz, der ordner _Impfungen unter Deutschland wird nicht mehr benutzt

**Comment by DutchmanNL** [comment]
> Danke. Gefunden und geht 👍

dan mache ich hier mal zu :)
