### ISSUE TITLE
Meldung Falscher Typ seit admin 5

### ISSUE THREAD

**Issue by Farmer-cb** [DrozmotiX/ioBroker.coronavirus-statistics#312]
Hallo
seit dem Update auf Admin 5 bekomme ich mein log mit folgenden Meldungen gefüllt:

`
<html>
<body>

coronavirus-statistics.0 | 2021-08-17 13:00:10.976 | info | (4125) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
-- | -- | -- | --
coronavirus-statistics.0 | 2021-08-17 13:00:10.870 | info | (4125) State value to set for "coronavirus-statistics.0.Germany.Kreis.Nürnberger_Land.BL" has to be type "number" but received type "string"
coronavirus-statistics.0 | 2021-08-17 13:00:10.802 | info | (4125) State value to set for "coronavirus-statistics.0.Germany.Stadt.Nürnberg.BL" has to be type "number" but received type "string"
coronavirus-statistics.0 | 2021-08-17 13:00:10.721 | info | (4125) State value to set for "coronavirus-statistics.0.Germany.Kreis.Schwandorf.BL" has to be type "number" but received type "string"
coronavirus-statistics.0 | 2021-08-17 13:00:10.664 | info | (4125) State value to set for "coronavirus-statistics.0.Germany.Kreis.Regensburg.BL" has to be type "number" but received type "string"
coronavirus-statistics.0 | 2021-08-17 13:00:10.584 | info | (4125) State value to set for "coronavirus-statistics.0.Germany.Kreis.Neumarkt_id_OPf.BL" has to be type "number" but received type "string"
coronavirus-statistics.0 | 2021-08-17 13:00:10.517 | info | (4125) State value to set for "coronavirus-statistics.0.Germany.Kreis.Amberg-Sulzbach.BL" has to be type "number" but received type "string"
coronavirus-statistics.0 | 2021-08-17 13:00:10.460 | info | (4125) State value to set for "coronavirus-statistics.0.Germany.Stadt.Regensburg.BL" has to be type "number" but received type "string"
coronavirus-statistics.0 | 2021-08-17 13:00:10.375 | info | (4125) State value to set for "coronavirus-statistics.0.Germany.Stadt.Amberg.BL" has to be type "number" but received type "string"
coronavirus-statistics.0 | 2021-08-17 13:00:09.875 | info | (4125) State value to set for "coronavirus-statistics.0.country_Top_5.5.testsPerOneMillion" has to be type "string" but received type "number"
coronavirus-statistics.0 | 2021-08-17 13:00:09.856 | info | (4125) State value to set for "coronavirus-statistics.0.country_Top_5.5.tests" has to be type "string" but received type "number"
coronavirus-statistics.0 | 2021-08-17 13:00:09.623 | info | (4125) State value to set for "coronavirus-statistics.0.country_Top_5.4.testsPerOneMillion" has to be type "string" but received type "number"
coronavirus-statistics.0 | 2021-08-17 13:00:09.617 | info | (4125) State value to set for "coronavirus-statistics.0.country_Top_5.4.tests" has to be type "string" but received type "number"
coronavirus-statistics.0 | 2021-08-17 13:00:09.481 | info | (4125) State value to set for "coronavirus-statistics.0.country_Top_5.3.testsPerOneMillion" has to be type "string" but received type "number"
coronavirus-statistics.0 | 2021-08-17 13:00:09.472 | info | (4125) State value to set for "coronavirus-statistics.0.country_Top_5.3.tests" has to be type "string" but received type "number"
coronavirus-statistics.0 | 2021-08-17 13:00:09.244 | info | (4125) State value to set for "coronavirus-statistics.0.country_Top_5.2.testsPerOneMillion" has to be type "string" but received type "number"
coronavirus-statistics.0 | 2021-08-17 13:00:09.234 | info | (4125) State value to set for "coronavirus-statistics.0.country_Top_5.2.tests" has to be type "string" but received type "number"
coronavirus-statistics.0 | 2021-08-17 13:00:08.880 | info | (4125) State value to set for "coronavirus-statistics.0.country_Top_5.1.testsPerOneMillion" has to be type "string" but received type "number"
coronavirus-statistics.0 | 2021-08-17 13:00:08.846 | info | (4125) State value to set for "coronavirus-statistics.0.country_Top_5.1.tests" has to be type "string" but received type "number"
coronavirus-statistics.0 | 2021-08-17 13:00:06.916 | info | (4125) State value to set for "coronavirus-statistics.0.Germany.testsPerOneMillion" has to be type "string" but received type "number"
coronavirus-statistics.0 | 2021-08-17 13:00:06.906 | info | (4125) State value to set for "coronavirus-statistics.0.Germany.tests" has to be type "string" but received type "number"
coronavirus-statistics.0 | 2021-08-17 13:00:05.856 | info | (4125) State value to set for "coronavirus-statistics.0.global_totals.testsPerOneMillion" has to be type "string" but received type "number"
coronavirus-statistics.0 | 2021-08-17 13:00:05.802 | info | (4125) State value to set for "coronavirus-statistics.0.global_totals.tests" has to be type "string" but received type "number"

</body>
</html>
`

**Comment by DutchmanNL** [comment]
ist bereits in der letzten beta gefixt, erwarte die am WE auf stable zu publizieren
