### ISSUE TITLE
Hospitalisierungsrate Bayern

### ISSUE THREAD

**Issue by chrkraus** [DrozmotiX/ioBroker.coronavirus-statistics#318]
Hallo @DutchmanNL,

In **Bayern** haben sich die Gesetze geändert. Ab den **02.09.2021** wird nicht mehr der 7-Tages Inzident der Neuansteckung als Grundlage verwendet sondern die **Hospitalisierungsrate**. Hierzu habe ich folgende Tabelle gefunden:

https://www.intensivregister.de/#/aktuelle-lage/laendertabelle

Könnte man diese Daten in dem Corona Adapter mit aufnehmen?

- Wieviel Betten im Krankenhaus sind wegen Corona gerade in Bayern  belegt
- Wieviel Patienten sind im Krankenhaus, in Bayern gerade wegen Corona auf der Intensiv-Station

Ich verwende derzeit diesen Adapter im ioBroker um ca. 300 täglich  Einwohner (im Landkreis) mit den aktuellen Zahlen über Telegramm zu informieren. Wäre super, wenn wir auch die neuen Daten täglich melden könnten.

Vielen herzlichen Dank.
Christian Kraus

P. S.: Spende ist überwiesen :-)

**Comment by DutchmanNL** [comment]
wen du dich traust darfst gerne die git version probieren, gerade gestern de PR gemerged fuer Krankenhaus Daten mit grossen dank an @jlssmt https://github.com/DrozmotiX/ioBroker.coronavirus-statistics/commit/be5eafcc23d4ac8ca1b82402f11ae9b15844d36f

Werde heute oder morgen eine 0.6.1 als beta veröffentlichen

**Comment by DutchmanNL** [comment]
> Ich verwende derzeit diesen Adapter im ioBroker um ca. 300 täglich Einwohner (im Landkreis) mit den aktuellen Zahlen über Telegramm zu informieren. Wäre super, wenn wir auch die neuen Daten täglich melden könnten.

Sehr interessanter. use case ! Glaube das hier ist was du suchst ?

<img width="1498" alt="Schermafbeelding 2021-09-01 om 10 21 19" src="https://user-images.githubusercontent.com/7318445/131637688-5cd1bf5c-187a-4f69-9133-b49bb6f349d7.png">

**Comment by chrkraus** [comment]
> wen du dich traust darfst gerne die git version probieren, gerade gestern de PR gemerged fuer Krankenhaus Daten mit grossen dank an @jlssmt [be5eafc](https://github.com/DrozmotiX/ioBroker.coronavirus-statistics/commit/be5eafcc23d4ac8ca1b82402f11ae9b15844d36f)
> 
> Werde heute oder morgen eine 0.6.1 als beta veröffentlichen
> 
> > P. S.: Spende ist überwiesen :-)
> 
> ich bedanke mich sehr, neue Projekte stehen bereits auf de liste :)

Kannst Du mir einen Tipp geben, wie ich diese Version in ioBroker aktualisiere?

**Comment by DutchmanNL** [comment]
> > wen du dich traust darfst gerne die git version probieren, gerade gestern de PR gemerged fuer Krankenhaus Daten mit grossen dank an @jlssmt [be5eafc](https://github.com/DrozmotiX/ioBroker.coronavirus-statistics/commit/be5eafcc23d4ac8ca1b82402f11ae9b15844d36f)
> > Werde heute oder morgen eine 0.6.1 als beta veröffentlichen
> > > P. S.: Spende ist überwiesen :-)
> > 
> > 
> > ich bedanke mich sehr, neue Projekte stehen bereits auf de liste :)
> 
> Kannst Du mir einen Tipp geben, wie ich diese Version in ioBroker aktualisiere?

ist im moment nog in alpha test fase, unter adapter den Expertenmodus aktivieren und dan oben rechts das Katzen symbol.
rechtes tab "url von git"

**Comment by jlssmt** [comment]
@DutchmanNL
Den selben use case habe ich übrigens auch. Informiere auch Bekannte per telegram über die aktuellen Zahlen.
Deshalb bin ich auch drauf gekommen das überhaupt umzusetzen ;) 

@chrkraus
Geb bitte Bescheid, ob die Implementierung passt.

**Comment by Stefan592** [comment]
Ich habe die neue Version nicht geprüft, anhand des Screenshots ist aber eine Umsetzung der Ampel momentan nicht möglich.

> > <img alt="Schermafbeelding 2021-09-01 om 10 21 19" width="1498" src="https://user-images.githubusercontent.com/7318445/131637688-5cd1bf5c-187a-4f69-9133-b49bb6f349d7.png">

Voraussetzungen für Gelb oder Rot:
![image](https://user-images.githubusercontent.com/14180760/131657087-f17c5f65-9c76-4c4e-80f4-b54a722514ab.png)


Könnte man dies noch einbauen, vielleicht wird auch eine andere Datenquelle benötigt die diese Daten zur Verfügung stellt.
Leider konnte ich keine bessere wie die oben verlinkte finden.

**Comment by jlssmt** [comment]
@chrkraus 
Rot müsste darstellbar sein.

@DutchmanNL 
Für Gelb müssten wir eine Historie anlegen und dann selbst berechnen.
Für mich wäre das aktuell out-of-scope vom Adapter.

Die Grafik hier stellt das auch nicht da. Ich denke da wird zukünftig was kommen.
https://experience.arcgis.com/experience/3a132983ad3c4ab8a28704e9addefaba

**Comment by chrkraus** [comment]
Funktioniert soweit erstmal gut :-). Habs gleich mal implimentiert:

![image](https://user-images.githubusercontent.com/25742967/131663349-30e81b74-00e0-4e12-baa9-063d23d4e216.png). 

Ihr könnt gerne den Telegramm abonieren, falls Intresse besteht: https://t.me/nstwalnaabcovid19

Danke
Gruß Christian

**Comment by DutchmanNL** [comment]
> @chrkraus
> Rot müsste darstellbar sein.

jup, ist ja im gründe der wert > x

> @DutchmanNL
> Für Gelb müssten wir eine Historie anlegen und dann selbst berechnen.
> Für mich wäre das aktuell out-of-scope vom Adapter.

dem stimme ich zu, wuerde bedeuten das wir manuell die sieben tagen incidenz beibehalten was auch per script möglich ist und ich erwarte das die API das bereit stellen wird eventuell ein issue

**Comment by jlssmt** [comment]
@chrkraus
Ah, ne danke. Ich habe das schon mit verschiedenen Kreisen :-)

**Comment by DutchmanNL** [comment]
> Ihr könnt gerne den Telegramm abonieren, falls Intresse besteht: https://t.me/nstwalnaabcovid19

wird doch glatt gemacht ich freue mich zu sehen was ihr so alles mit unseren gebastel anstellt :)

**Comment by jlssmt** [comment]
@DutchmanNL 

die ampel werte gibts jetzt hier. ist halt keine api und daher nicht stable für mich. könnte aber ne version publishen, wenn du willst.
https://www.lgl.bayern.de/gesundheit/infektionsschutz/infektionskrankheiten_a_z/coronavirus/karte_coronavirus/index.htm

**Comment by DutchmanNL** [comment]
> @DutchmanNL
> 
> die ampel werte gibts jetzt hier. ist halt keine api und daher nicht stable für mich. könnte aber ne version publishen, wenn du willst.
> https://www.lgl.bayern.de/gesundheit/infektionsschutz/infektionskrankheiten_a_z/coronavirus/karte_coronavirus/index.htm
> 
> **BAYERN ONLY!!!**

Hmm währe wieder ein cvs Import damit hatten wir bereits einige Probleme ich warte lieber bis es per api verfügbar ist um es integrieren zu können

**Comment by jlssmt** [comment]
@DutchmanNL
Csv? Die hab ich nicht mal gefunden :-D
Hätte die Tabelle geparst :-D

**Comment by herrxyz** [comment]
beim stöbern (https://services7.arcgis.com/mOBPykOjAyBO2ZKk/ArcGIS/rest/services) fiel mir auf, dass es auch ein "DIVI_Intensivregister_Landkreise (FeatureServer)" gibt, da könnten die gesuchten Daten drin sein
https://services7.arcgis.com/mOBPykOjAyBO2ZKk/ArcGIS/rest/services/DIVI_Intensivregister_Landkreise/FeatureServer/0

bin noch am rätseln wie ich die Daten vernünftig auslesen kann, als zwischenstand bekomme ich mit
https://services7.arcgis.com/mOBPykOjAyBO2ZKk/ArcGIS/rest/services/DIVI_Intensivregister_Landkreise/FeatureServer/0/query?where=1%3D1&outFields=betten_frei&geometry=8.253%2C49.046&county&BL_ID&BL&geometryType=esriGeometryPoint&inSR=4326&spatialRel=esriSpatialRelWithin&returnGeometry=false&outSR=4326&f=json aber zumindest eine lesbare antwort (5 Betten)

**Comment by herrxyz** [comment]
ich muss aber zugeben, ich habe nicht wirklich rausfinden können was die echte datenquelle dieser seite ist, aber es wirkt irgendwie wie was offizielles
lese von dort auch seit monaten täglich inzidenzen für ein paar Landkreise in meiner Umgebung aus, habe diese aber nie mit irgendwelchen offiziellen werten verglichen ;-(
ich kann ggf. auch den Link dazu posten

**Comment by DutchmanNL** [comment]
> mögliche weitere parameter sind auf der Übersichtsseite zu finden (siehe mein vorvorheriger Post)

Welche Daten suchst du den? Krankenhaus Daten sind ja bereits drin…

**Comment by herrxyz** [comment]
ich suche nichts mehr, das war falls du noch irgendwas zu meinem beispiel-link hinzufügen möchtest

**Comment by jlssmt** [comment]
@herrxyz
Was wir insbesondere benötigen, ist die 7-Tage-Hospitalisierungsrate. 
Die ist aktuell der Maßstab in Bayern, aber ich nehme an, dass andere Bundesländer nachziehen werden.

**Comment by ElDiabolus** [comment]
Erst mal vielen Dank für die tolle API! @DutchmanNL 

Ich bin gerade ein wenig verwirrt. Rot kann man berechnen, indem man IntensivBettenBelegt*CovidToIntensivBettenPercent berechnet richtig? + Dementsprechend noch die 7 Tage Insidenz.
Gibt es schon News dazu, ob es bald die 7-Tage-Hospitalisierungs-Inzidenz pro 100.000 Einwohner geben wird? Wäre sehr interessant. Gibt es vielleicht auch eine genauere Beschreibung der bisherigen Zahlen? Mir ist zum Beispiel nicht klar, was intensivBettenNotfall7d, oder meldebereichAnz ist.

Danke

**Comment by jlssmt** [comment]
@ElDiabolus 
Ich weiß gerade nicht wie die Ampeln in allen Bundesländern berechnet werden, oder ob es eine deutschlandweite Regelung gibt.
Für Bayern kann ich sagen: Rot ist die Ampel, wenn der Wert `coronavirus-statistics.0.Germany.Bundesland.Bayern.Hospital.faelleCovidAktuell` über 600 liegt. Also musst man da nichts berechnen.
Für Gelb müsste der Adapter die letzten 7-Tage der COVID-Neueinlieferungen als Historie abspeichern. Hierfür stellt aber die DIVI-API weder den Wert für die COVID-Neueinlieferungen, noch den Wert für ebendiesen 7-Tage Wert bereit.

Was genau intensivBettenNotfall7d oder meldebereichAnz ist, weiß ich auch nicht. Diese Werte liefert halt die DIVI-API. Infos zu dieser API findest du hier. Wenn du rausfindest, was die Werte bedeuten können wir das gerne im Namen des ioBroker-Datenpunkts ergänzen.

https://www.intensivregister.de/api/public/swagger-ui/index.html?configUrl=/api/public/api-docs/swagger-config#/laendertabelle-public-controller/getPublicLaendertabelle

https://www.divi.de/register/tagesreport

**Comment by lindi200000** [comment]
Jedes Bundesland hat da sein eigenes Konzept.
Niedersachsen z.b. Höhe der ‚Hospitalisierung‘ + min ‚Neuinfizierte‘ ODER ‚Intensivbetten‘ übereinen bestimmten Wert,

**Comment by jlssmt** [comment]
Hmm OK. Ja wie gesagt. Ich kann nur liefern was DIVI auch anbietet. Siehe links oben.

**Comment by chrkraus** [comment]
@DutchmanNL : Ich habe eine neue Seite zur Krankenhausampel Bayern entdeckt :-). Vielleicht könnte die man integrieren (wenn nicht schon geschehen):

Quellen von der Seite sind:
https://corona-ampel-bayern.de/
https://api.corona-zahlen.org/docs/ 
https://www.intensivregister.de/#/index
https://www.lgl.bayern.de/gesundheit/infektionsschutz/infektionskrankheiten_a_z/coronavirus/karte_coronavirus/index.htm

**Comment by chrkraus** [comment]
@DutchmanNL : schau mal hier :-): 
https://www.i-novation.de/corona-ampel-bayern/#api

das wäre doch was :-)

**Comment by lindi200000** [comment]
Da der Adapter sehr allgemein gehalten ist, finde ich es besser wenn sowas Deutschlandweit integriert wird. Am ende will dann jemand das für den LK haben, für die Stadt oder dann das Bundesland. Finde ich persönlich nicht gerade praktisch.

**Comment by DutchmanNL** [comment]
Lokale api's werden wir nicht einbinden der Aufwand dafür ist viel zu hoch. Algemeine Schnittstellen welche Daten für ganz DE liefern schauen wir uns gerne an

**Comment by DutchmanNL** [comment]
Ich schliesse dieses isst erstmal da wir keine allgemeine source fuer die daten haben. Sollte jemand dennoch fündig werden öffne ich es gerne wieder und schauen wir es uns an
