### ISSUE TITLE
Can you include r value / R-Wert in the dataset?

### ISSUE THREAD

**Issue by enzo771** [DrozmotiX/ioBroker.coronavirus-statistics#329]
This is an excellent adapter.

The one value I'm missing is the r value, i.e. "R-Wert" in German as published daily by the RKI for Germany, s. last three columns in csv file:
[](https://github.com/robert-koch-institut/SARS-CoV-2-Nowcasting_und_-R-Schaetzung/blob/main/Nowcast_R_aktuell.csv)

As in indicator for the development of infection rates I would like to follow it regularly and compare its development with the development of cases.

Would it be difficult to include it in the dataset?

**Comment by DutchmanNL** [comment]
not sure if its included in the API dataset, can you please have a look at these attributes if your value is in there ?

Vaacination data 👍 

```
      "BW": {
        "name": "Baden-Württemberg",
        "administeredVaccinations": 14478846,
        "vaccinated": 7405728,
        "vaccination": {
          "biontech": 5249386,
          "moderna": 553662,
          "astraZeneca": 1174461,
          "janssen": 428219
        },
        "delta": 2965,
        "quote": 0.667,
        "secondVaccination": {
          "vaccinated": 7214659,
          "vaccination": {
            "biontech": 5729862,
            "moderna": 658292,
            "astraZeneca": 398286
          },
          "delta": 4296,
          "quote": 0.65
        },
        "boosterVaccination": {
          "vaccinated": 286678,
          "vaccination": {
            "biontech": 276967,
            "moderna": 9704,
            "janssen": 6
          },
          "delta": 7076
        },
        "indication": {
          "age": null,
          "job": null,
          "medical": null,
          "nursingHome": null,
          "secondVaccination": {
            "age": null,
            "job": null,
            "medical": null,
            "nursingHome": null
          }
        }
      },
```

Hospital Data:

```
    {
      "creationTimestamp": "2021-11-03T13:40:14Z",
      "bundesland": "SCHLESWIG_HOLSTEIN",
      "meldebereichAnz": 38,
      "standortAnzahl": 31,
      "faelleCovidAktuell": 23,
      "faelleCovidAktuellBeatmet": 13,
      "intensivBettenBelegt": 624,
      "intensivBettenFrei": 143,
      "intensivBettenFreiProStandort": 4.612903225806452,
      "covidKapazitaetFrei": 44,
      "intensivBettenGesamt": 767,
      "intensivBettenNotfall7d": 466,
      "covidToIntensivBettenPercent": 3.0,
      "faelleCovidAktuellBeatmetToCovidAktuellPercent": 56.52,
      "bettenBelegtToBettenGesamtPercent": 81.36,
      "bettenFreiToBettenGesamtPercent": 18.64
    },
```

**Comment by enzo771** [comment]
No, it's neither in the vaccination nor hospital data, it's related to infection rates.

I have also not found it in the sources you quote: [npgeo](https://npgeo-corona-npgeo-de.hub.arcgis.com/) or [wordometers](https://www.worldometers.info/coronavirus/).

For Germany, the r values are available through [SARS-CoV-2-Nowcasting und -R-Schätzung](https://github.com/robert-koch-institut/SARS-CoV-2-Nowcasting_und_-R-Schaetzung): In the daily file [Nowcast_R_aktuell.csv](https://github.com/robert-koch-institut/SARS-CoV-2-Nowcasting_und_-R-Schaetzung/blob/main/Nowcast_R_aktuell.csv) there are three columns on the right:

PS_7_Tage_R_Wert | UG_PI_7_Tage_R_Wert | OG_PI_7_Tage_R_Wert,
being the best estimate (7-day r value of Germany) and its the lower and upper border of the 95% prediction interval.

**Comment by DutchmanNL** [comment]
Ok ir would be great if the data will be available by the vaccination data source for Germany as, sorry to be that explicit, will not again include csv files from rki as this would result in a lot of maintenance work on the adapter.  

Rki is changing their way of data structures almost every week it’s impossible for me (fully free and open source minded) to maintain and monitor the Adapter every week so I have to rely on trusted sources

you may could raise an issue at the German vac api to include this date ? Then we can incorporate the content.

sorry being throat roughly, but better to be specific with a clear statement then talking in clouds right 😉?

**Comment by enzo771** [comment]
Thanks for the reply, fully understood on the premise of maintenance required on a csv file. I appreciate clear words.

**Comment by enzo771** [comment]
I did some more research:
the R value is actually available in the [api on German Corona data](https://api.corona-zahlen.org/) already use:
The request on R value as [endpoint](https://api.corona-zahlen.org/docs/endpoints/germany.html) should run as

GET https://api.corona-zahlen.org/germany

Then take "r" from the response:
{
  "cases": 4472730,
  "deaths": 95117,
  "recovered": 4215170,
  "weekIncidence": 110.06189150479662,
  "casesPer100k": 5378.7845981321325,
  "casesPerWeek": 91522,
  "delta": {
    "cases": 6573,
    "deaths": 17,
    "recovered": 8811
  },
  "r": {
    "value": 1.18,
    "rValue4Days": {
      "value": 1.18,
      "date": "2021-10-21T00:00:00.000Z"
    },
    "rValue7Days": {
      "value": 1.17,
      "date": "2021-10-20T00:00:00.000Z"
    },
    "lastUpdate": "2021-10-24T23:48:33.000Z"
  },
  "hospitalization": {
    "cases7Days": 2303,
    "incidence7Days": 2.77,
    "date": "2021-10-25T00:00:00.000Z",
    "lastUpdate": "2021-10-25T02:01:53.000Z"
  },
  "meta": {
    "source": "Robert Koch-Institut",
    "contact": "Marlon Lueckert (m.lueckert@me.com)",
    "info": "https://github.com/marlon360/rki-covid-api",
    "lastUpdate": "2021-10-24T23:00:00.000Z",
    "lastCheckedForUpdate": "2021-10-25T11:06:58.517Z"
  }
}

**Comment by DutchmanNL** [comment]
German api's are closed and data not available, adapter will remain for global API and German specific implementations (which I already was afraid for during implementation) are not maintained anymore and therefore not usable
