### ISSUE TITLE
Warmmeldungen State attribute definition missing

### ISSUE THREAD

**Issue by sigi2345** [DrozmotiX/ioBroker.coronavirus-statistics#331]
Hallo,

folgende Warnmeldungen kommen :

  | 2021-11-17 10:14:42.439 warn State attribute definition missing for daily_people_vaccinated_per_hundred
  |  
  | coronavirus-statistics.0
  | 2021-11-17 10:14:42.439 debug Create_state called for : United_Kingdom.Vaccination.daily_people_vaccinated_per_hundred with value : 0.067
  |  
  | coronavirus-statistics.0
  | 2021-11-17 10:14:42.383 debug Write value : false
  |  
  | coronavirus-statistics.0
  | 2021-11-17 10:14:42.383 warn State attribute definition missing for daily_people_vaccinated
  |  
  | coronavirus-statistics.0
  | 2021-11-17 10:14:42.383 debug Create_state called for : United_Kingdom.Vaccination.daily_people_vaccinated with value : 45681

--------------------------------------------------------------------------------------------------------------------------------------------
Version 0.8.6 
node: v12.22.7
js-controller: 3.3.18

**Comment by DutchmanNL** [comment]
Please try 0.8.7-0 from git

**Comment by sigi2345** [comment]
> Please try 0.8.7-0 from git

Warn weg.
