### ISSUE TITLE
Some information missing

### ISSUE THREAD

**Issue by rde29** [DrozmotiX/ioBroker.coronavirus-statistics#334]
Hello, I recongnized that some attributes in structure will not be filled,
especially the current figures of corona:

coronavirus-statistics.0.Germany.todayCases
coronavirus-statistics.0.Germany.todayDeaths

My adapter Version is 0.8.7

**Comment by DutchmanNL** [comment]
Will Check, wouldn’t surprise me if those values are removed from api

**Comment by valbuz** [comment]
Hi
For me the same….
Cases today show´s always the same counter since  a few days.
(Country: switzerland)

thanks
Pat

**Comment by DutchmanNL** [comment]
I am sorry but cannot fix this one, the API does not provide that data anymore only for a total value of all countries combined
(see https://disease.sh/v3/covid-19/countries?sort=cases)

API provider can also not fix it as the source is not providing it anymore, see https://github.com/disease-sh/API/issues/647
