### ISSUE TITLE
Delete States bei Bundesländern

### ISSUE THREAD

**Issue by jlssmt** [DrozmotiX/ioBroker.coronavirus-statistics#336]
Wenn man mehrere Bundesländer auswählt und dann wieder abwählt, werden die Ordner Hospital und Hospital-Index nicht gelöscht. Damit wird auch der ganze Channel fürs Bundesland nicht gelöscht.

Ich schreibs hier mal als Merker rein.

**Comment by DutchmanNL** [comment]
da die API fuer Bundesländer nicht mehr aktiv is werde ich diese entfernen müssen
