### ISSUE TITLE
Wrong numbers

### ISSUE THREAD

**Issue by Tscho32** [DrozmotiX/ioBroker.coronavirus-statistics#337]
For several weeks I have been receiving incorrect numbers for the new cases every day.
Today I see 5397 cases although the official number is 9941. The timestamp is current.
I talk about the cases for Switzerland

![Bildschirmfoto 2021-12-17 um 14 38 01](https://user-images.githubusercontent.com/87376051/146553020-ecbfb795-cc27-4b78-ad64-e49d9ff9d1f8.png)

**Versions:**  
 - Adapter version: v0.8.7
 - JS-Controller version: 3.3.21
 - Node version: 14.18.12
 - Operating system: <os-buster> Raspberry Pi 4

**Comment by DutchmanNL** [comment]
I cannot manipulate the data coming from all sources :),  https://github.com/disease-sh/API/issues/647
