### ISSUE TITLE
js-controller 4 Meldungen 

### ISSUE THREAD

**Issue by Pocky2507** [DrozmotiX/ioBroker.coronavirus-statistics#340]
`

coronavirus-statistics.0 | 2022-02-06 13:42:02.602 | warn | (642777) This object will not be created in future versions. Please report this to the developer.
-- | -- | -- | --
coronavirus-statistics.0 | 2022-02-06 13:42:02.599 | warn | (642777) Object coronavirus-statistics.0.countryTranslator is invalid: Default value has to be type "string" but received type "number"

`

**Comment by DutchmanNL** [comment]
#347 is related

**Comment by DutchmanNL** [comment]
fixed in git, will make a new release this week
