### ISSUE TITLE
Wrong Object type

### ISSUE THREAD

**Issue by Draexl** [DrozmotiX/ioBroker.coronavirus-statistics#347]
Got the following message in the log:
`Object coronavirus-statistics.0.countryTranslator is invalid: Default value has to be type "string" but received type "number"`

**Comment by haselchen** [comment]
Me too  :)

<html><body>


coronavirus-statistics.0 | 2022-03-19 15:45:04.621 | warn | (3711) This object will not be created in future versions. Please report this to the developer.
-- | -- | -- | --
coronavirus-statistics.0 | 2022-03-19 15:45:04.620 | warn | (3711)  Object coronavirus-statistics.0.countryTranslator is invalid: Default  value has to be type "string" but received type "number"


</body>
</html>

**Comment by mest2** [comment]
Hallo,
ich habe das Problem auch seit geraumer Zeit.
Ich würde mich sehr freuen wenn es beseitigt werden könnte.

VG und Danke für die ganze Arbeit.

**Comment by jhg28** [comment]
Same here.

**Comment by Alpakat** [comment]
+1

**Comment by macpo** [comment]
+1

**Comment by DutchmanNL** [comment]
fixed in git, will make a new release this week
