### ISSUE TITLE
US "active" Data is not being filled anymore

### ISSUE THREAD

**Issue by theGrinchUK** [DrozmotiX/ioBroker.coronavirus-statistics#349]
Compared to the Germany numbers, in the US folder I have several 0 sind June 27th.
e.g. coronavirus-statistics.0.United_States.activePerOneMillion
Did they stop reporting? Or change a URL maybe?

**Comment by DutchmanNL** [comment]
that was an temporary API issue, if API does not provide the values adapter can indeed not write it.
looking now all seems to look ok

<img width="1327" alt="Screenshot 2023-09-21 at 22 57 02" src="https://github.com/DrozmotiX/ioBroker.coronavirus-statistics/assets/7318445/4112d53f-5c57-4504-986e-317dbc15cd2b">
