### ISSUE TITLE
Error Message Wrong type

### ISSUE THREAD

**Issue by jhg28** [DrozmotiX/ioBroker.coronavirus-statistics#350]
Following Error-Message with Admin 6:

2022-07-30 20:00:05.741 | warn | This object will not be created in future versions. Please report this to the developer.
coronavirus-statistics.0 | 2022-07-30 20:00:05.735 | warn | Object coronavirus-statistics.0.countryTranslator is invalid: Default value has to be type "string" but received type "number

Occurs every time, when the adapter runs.

**Comment by Milbert-R** [comment]
coronavirus-statistics.0 | 3921440 | 2022-12-06 21:15:04.948 | warn | This object will not be created in future versions. Please report this to the developer.
coronavirus-statistics.0 | 3921440 | 2022-12-06 21:15:04.947 | warn | Object coronavirus-statistics.0.countryTranslator is invalid: Default value has to be type "string" but received type "number"

**Comment by DutchmanNL** [comment]
pr merged
