### ISSUE TITLE
No Current German Cases

### ISSUE THREAD

**Issue by brennermax** [DrozmotiX/ioBroker.coronavirus-statistics#352]
Leider werden keine tagesaktuellen Cases mehr ausgegeben. Die Zahl ist nur noch „0“.

**Comment by DutchmanNL** [comment]
Dan liefert die api diese Daten nicht mehr mir ist keine neue Struktur bzw Version bekannt.

Siehe readme für die verwendete source

**Comment by brennermax** [comment]
Gibt es eine andere API, die man nutzen könnte?

**Comment by DutchmanNL** [comment]
> Gibt es eine andere API, die man nutzen könnte?

leider nien, jedenfalls nicht soweit mir bekannt damit is die DE local spezifische daten nicht mehr integrierbar
