### ISSUE TITLE
Update stable version in repo from 0.8.7 to 0.9.0

### ISSUE THREAD

**Issue by GermanBluefox** [DrozmotiX/ioBroker.coronavirus-statistics#362]
# Think about update stable version to 0.9.0
**Version**: stable=**0.8.7** (744 days old) => latest=**0.9.0** (15 days old)
**Installs**: stable=**1937** (79.29%), latest=**154** (6.3%), total=**2443**

Click to use [developer portal](https://www.iobroker.dev/adapter/coronavirus-statistics/releases)
Click to [edit](https://github.com/ioBroker/ioBroker.repositories/edit/master/sources-dist-stable.json#L353)

Note: This is an automatically generated message and not personally authored by bluefox!

**Comment by mcm1957** [comment]
Is there any reason to delay update to stable any longer?

Please comment if there's a reason.

**Note: If there is no comment until 22.12.2023 the update could be performed anyway.**

**Comment by mcm1957** [comment]
A kind reminder ...

Please respond if anything know to avoid update, otherwise I will update at stable next week.

**Comment by GermanBluefox** [comment]
This issue seems to be outdated.

This issue suggests to update the stable version of this adapter to 0.9.0 but the current stable version is already 0.9.0.

So this issue should be closed.
